### ISSUE TITLE
JOSS REVIEW: Clarifying installation details

### ISSUE THREAD

**Issue by mathieuboudreau** [imr-framework/virtual-scanner#25]
This is for openjournals/joss-reviews#1637

In your installation instructions in your README, could you please:

1 - Specify which Python version (e.g. 3.6.x) or range of versions (e.g. 3.6-3.7) that you intend this software to be compatible with?
2 - As you are recommending people to install a lot of specific external python package & exact versions, it would be best practice to suggest to the user to install these in some sort of virtual environment so that these don't mess up their base environment (e.g. using [`conda`](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) or [`venv`](https://docs.python.org/3/library/venv.html), but I prefer `conda` via [miniconda](https://docs.conda.io/en/latest/miniconda.html) as it also allows for users to specify the python version of the environment).
3 - To make it easier on some folks who may be less familiar with bulk Python package installations, it would be helpful to recommend that they install all the `requirements.txt` packages using the command `pip install -e .` inside your folder, to avoid them to manually install each of them one at a time. Other solutions could work too, this is just my preferred installation workflow.

**Comment by sairamgeethanath** [comment]
@mathieuboudreau We will update the install instructions but we use Python 3.6 and [venv](https://docs.python.org/3/library/venv.html). I request you to use the same for reproducible results. You can pip install the package as well with pip install virtual-scanner

**Comment by mathieuboudreau** [comment]
Thanks! I did use 3.6 (but prefer conda over venv, as venv will only use your default python version and can't set it to a different one, and my default one is 3.7)

 However just to let you know that I encountered the issue #24 in when trying to install using `pip install virtual-scanner`, so you may want to investigate that.

**Comment by sravan953** [comment]
@mathieuboudreau Thank you for your inputs, they've been addressed in b42f9099812e2024ab4541c47f5b4a23b040a500.

**Comment by mathieuboudreau** [comment]
FYI, the issue is still not resolved for me. Trying the latest `pip` version of your software (1.0.24), I can't even access the server now, I just get this error on my terminal when running `virtualscanner`:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "/Users/mathieuboudreau/anaconda3/envs/vs_pypi/bin/virtualscanner", line 10, in <module>
    sys.exit(launch_virtualscanner())
  File "/Users/mathieuboudreau/anaconda3/envs/vs_pypi/lib/python3.6/site-packages/virtualscanner/coms/coms_ui/coms_server_flask.py", line 526, in launch_virtualscanner
    __modify_search_path()
  File "/Users/mathieuboudreau/anaconda3/envs/vs_pypi/lib/python3.6/site-packages/virtualscanner/coms/coms_ui/coms_server_flask.py", line 9, in __modify_search_path
    SEARCH_PATH = script_path[:script_path.index('virtual-scanner') + len('virtual-scanner') + 1]
ValueError: substring not found
```

On a side note: it may be a good idea for you folks to setup a continuous testing suite, using something like Travis-CI (free). Several commits made during this JOSS review introduced new bugs that were later found by manual testing from external users (like me), so for better software stability it would be useful if you were alerted immediately before users experience these bugs. Another thing that can improve stability is not pushing directly to master, but instead pushing to branches and only merging to master after the tests pass (and ideally, a code review too). JOSS even recommends this in their review guideline (though it's not required, I'm just pointing out how beneficial for you it would be to spend a little bit of time setting this up, for long term benefits).

**Comment by mathieuboudreau** [comment]
Dug in a bit deeper, this recent commit works if I run `virtualscanner` after I `git clone` the repo and install it using `pip install -e .`, just not if I install it through `pip install virtual-scanner`. Maybe has to do with the fact that when installed using `pip install virtual-scanner`, it's installed in a folder called `virtualscanner` and not `virtual-scanner` in the venv folder (i.e. only your module/subfolder [virtualscanner](https://github.com/imr-framework/virtual-scanner/tree/master/virtualscanner) is copied with this installation, vs. the `pip install -e .` installation which links to the cloned folder ?
